version: '3.7'

services:
  mongo_db:
    image: mongodb/mongodb-community-server:4.4-ubuntu2004
    container_name: weather_local_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: on-failure

  mongo_ui:
    image: mongo-express:1.0.0-alpha.4
    container_name: weather_local_mongo_ui
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:mongo@weather_local_mongo_db:27017?ssl=false"
      ME_CONFIG_OPTIONS_READONLY: "true"
      ME_CONFIG_OPTIONS_NO_DELETE: "false"
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - mongo_db

volumes:
  mongodb_data: